---
# First configuration file for Scala
# We will start our config file with the total number of bridges. 
# This way we can add (potentially remove) hikers.
# Next, we describe each bridge with its length. Next, we describe each 

# in this config file, we have three bridges
hikerbridges:
    - bridge: 
        length: 100.00      # length of 1st bridge is 100 feet
        hikers: [ 50.00, 20, 10.00 ]   # Initial hikers' speed: A to C
    - bridge:
        length: 250.00      # Length of the 2nd bridge is 250 feet
        hikers: [ 2.5 ]     # hiker D
    - bridge: 
        length: 150.00      # Length of the 3rd bridge is 150 feet
        hikers: [ 25.00, 15.00 ]    # hikers E & F